// Browser real, origem e perfil efêmeros; não acessa a instalação do usuário.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const http = require('node:http');
const path = require('node:path');
const { chromium } = require('playwright');

test('Ícones: arraste, teclado, cancelamento e persistência em perfil isolado', { timeout: 90000 }, async () => {
  const server = http.createServer((req, res) => {
    const file = new URL(req.url, 'http://localhost').pathname.replace(/^\/funtime\//, '') || 'index.html';
    if (file.includes('..') || file.startsWith('/')) return res.writeHead(404).end();
    try {
      const type = { '.js': 'text/javascript', '.html': 'text/html', '.css': 'text/css', '.webmanifest': 'application/manifest+json' }[path.extname(file)] || 'application/octet-stream';
      res.writeHead(200, { 'Content-Type': type }).end(fs.readFileSync(file));
    } catch { res.writeHead(404).end(); }
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const browser = await chromium.launch({ channel: process.env.PWA_BROWSER_CHANNEL || 'msedge', headless: true });
  try {
    const context = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true });
    await context.addInitScript(() => Object.defineProperty(navigator, 'standalone', { value: true }));
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto(`http://127.0.0.1:${server.address().port}/funtime/`);
    await page.getByRole('button', { name: 'Começar sem dados', exact: true }).click();
    for (const checkbox of await page.locator('#terms-form input[type=checkbox]').all()) await checkbox.check();
    await page.locator('#terms-continue').click();
    await page.waitForFunction(() => history.state?.funtimeNavigation && !document.body.classList.contains('boot-pending'));
    await page.evaluate(() => {
      state.drinks = [{ id: 'd', name: 'Teste', icon: '💧', intervalMinutes: 30, askDoseSize: false }];
      state.events = [{ id: 'e', drinkId: 'd', drinkName: 'Teste', drinkIcon: '💧', consumedAt: Date.now(), intervalMinutes: 30, doseSize: null }];
      saveData(); render();
    });
    await page.evaluate(() => openSettingsView());
    await page.locator('#touch-debug-panel summary').click();
    assert.equal(await page.locator('#touch-debug-enabled').isChecked(), false);
    assert.equal(await page.locator('#export-touch-debug').isDisabled(), true);
    await page.locator('label[for=touch-debug-enabled]').click();
    await page.evaluate(() => closeSettingsView());
    await page.evaluate(() => {
      persistIconCatalog(['💧', '🍺', '⭐', '🍷']);
      openEditDrinkDialog('d');
    });
    const order = () => page.evaluate(() => state.preferences.iconCatalog);
    const selected = () => page.locator('#icon-options input:checked').inputValue();
    const card = icon => page.locator(`[data-catalog-icon="${icon}"] > label`);
    const focus = icon => card(icon).locator('input').focus();
    const center = async locator => { const b = await locator.boundingBox(); return { x: b.x + b.width / 2, y: b.y + b.height / 2 }; };
    const original = ['💧', '🍺', '⭐', '🍷'];
    const settled = () => page.waitForFunction(() => [...document.querySelectorAll('[data-catalog-icon]')].every(node => !node.getAnimations().length));
    const compactHeight = await page.locator('#icon-options').evaluate(node => node.offsetHeight);
    assert.equal(await page.locator('.icon-move').count(), 0);
    await card('⭐').click(); assert.equal(await selected(), '⭐');
    await card('💧').click();
    await focus('💧'); await page.keyboard.press('Alt+End');
    assert.deepEqual(await order(), ['🍺', '⭐', '🍷', '💧']);
    await page.keyboard.press('Alt+Home'); assert.deepEqual(await order(), original);
    const begin = async icon => {
      await card(icon).scrollIntoViewIfNeeded();
      await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
      await settled();
      const a = await center(card(icon));
      await page.mouse.move(a.x, a.y); await page.mouse.down();
      assert.equal(await page.locator('.icon-drag-ghost').count(), 0);
      await page.waitForFunction(() => !!document.querySelector('.icon-drag-ghost'));
      assert.equal(await page.locator('#icon-trash').isVisible(), true);
    };
    const drag = async (to, cancel = false) => {
      const before = await order();
      await begin('💧');
      const b = to === 'trash' ? await center(page.locator('#icon-trash')) : to === 'outside' ? { x: 3, y: 120 } : await center(card(to));
      await page.mouse.move(b.x, b.y, { steps: 5 });
      assert.deepEqual(await order(), before, 'prévia não grava');
      if (to === 'trash') await page.waitForFunction(() => document.querySelector('#icon-trash').classList.contains('icon-trash-active'));
      else if (to !== 'outside') await page.waitForFunction(() => [...document.querySelectorAll('[data-catalog-icon]:not(.icon-dragging)')].some(node => node.style.transform && node.style.transform !== 'translate(0px, 0px)'));
      if (cancel) await page.keyboard.press('Escape');
      await page.mouse.up();
      assert.equal(await page.locator('.icon-drag-ghost').count(), 0);
      assert.equal(await page.locator('#icon-trash').isVisible(), false);
    };
    // Soltar após segurar, sem deslocamento, não seleciona nem reordena.
    await begin('⭐'); await page.mouse.up();
    assert.equal(await selected(), '💧'); assert.deepEqual(await order(), original);
    // Mover antes do prazo cancela a ativação.
    const a = await center(card('💧'));
    await page.mouse.move(a.x, a.y); await page.mouse.down(); await page.mouse.move(a.x + 20, a.y);
    await page.waitForTimeout(600); assert.equal(await page.locator('.icon-drag-ghost').count(), 0); await page.mouse.up();
    await drag('⭐', true); assert.deepEqual(await order(), original);
    await drag('outside'); assert.deepEqual(await order(), original);
    await drag('⭐'); assert.deepEqual(await order(), ['🍺', '⭐', '💧', '🍷']);
    await page.locator('#undo-icon-reorder').click(); assert.deepEqual(await order(), original);
    await drag('trash', true); assert.deepEqual(await order(), original);
    await begin('💧'); const trashPoint = await center(page.locator('#icon-trash'));
    await page.mouse.move(trashPoint.x, trashPoint.y);
    await page.waitForFunction(() => document.querySelector('#icon-trash').classList.contains('icon-trash-active'));
    await page.screenshot({ path: path.join(require('node:os').tmpdir(), 'funtime-icon-trash.png') });
    await page.mouse.up();
    assert.deepEqual(await order(), ['🍺', '⭐', '🍷']); assert.equal(await selected(), '💧');
    assert.equal(await page.evaluate(() => state.drinks[0].icon), '💧');
    assert.equal(await page.evaluate(() => state.events[0].drinkIcon), '💧');
    await page.locator('#undo-icon-removal').click(); assert.deepEqual(await order(), original);
    const cdp = await context.newCDPSession(page);
    const touch = (type, point) => cdp.send('Input.dispatchTouchEvent', { type, touchPoints: point ? [point] : [] });
    const touchDrag = async (destination, cancel = false) => {
      await settled();
      const a = await center(card('💧'));
      await touch('touchStart', a);
      await page.waitForFunction(() => !!document.querySelector('.icon-drag-ghost'));
      const b = destination === 'trash' ? await center(page.locator('#icon-trash')) : await center(card(destination));
      await touch('touchMove', b);
      await page.waitForFunction(() => !!document.querySelector('.icon-drag-ghost'));
      await touch(cancel ? 'touchCancel' : 'touchEnd');
    };
    await touchDrag('⭐', true); assert.deepEqual(await order(), original);
    // Contato largo e oscilação de 12px durante a espera não soltam o ícone.
    await settled();
    const broadStart = await center(card('💧'));
    await touch('touchStart', { ...broadStart, radiusX: 22, radiusY: 18, force: .4 });
    await touch('touchMove', { x: broadStart.x + 12, y: broadStart.y + 4, radiusX: 28, radiusY: 23, force: .5 });
    await page.waitForFunction(() => !!document.querySelector('.icon-drag-ghost'));
    await card('💧').dispatchEvent('pointercancel', { pointerType: 'touch', bubbles: true });
    assert.equal(await page.locator('.icon-drag-ghost').count(), 1);
    await touch('touchMove', { ...await center(card('⭐')), radiusX: 30, radiusY: 24, force: .3 });
    await touch('touchEnd');
    assert.deepEqual(await order(), ['🍺', '⭐', '💧', '🍷']);
    await page.locator('#undo-icon-reorder').click();
    await touchDrag('⭐'); assert.deepEqual(await order(), ['🍺', '⭐', '💧', '🍷']);
    await touchDrag('trash'); assert.deepEqual(await order(), ['🍺', '⭐', '🍷']);
    await page.locator('#undo-icon-removal').click(); assert.deepEqual(await order(), ['🍺', '⭐', '💧', '🍷']);
    await page.evaluate(() => { globalThis.originalSetItem = Storage.prototype.setItem; Storage.prototype.setItem = () => { throw new Error('quota'); }; });
    await drag('🍺'); assert.deepEqual(await order(), ['🍺', '⭐', '💧', '🍷']);
    await drag('trash'); assert.deepEqual(await order(), ['🍺', '⭐', '💧', '🍷']);
    assert.match(await page.locator('#icon-catalog-status').textContent(), /Não foi possível salvar/);
    await page.evaluate(() => { Storage.prototype.setItem = globalThis.originalSetItem; });
    await page.locator('.icon-edit').click();
    assert.equal(await page.locator('.icon-remove:visible').count(), 4);
    assert.equal(await page.locator('#icon-options').evaluate(node => node.offsetHeight), compactHeight);
    const disabledPoint = await center(card('💧'));
    await page.mouse.move(disabledPoint.x, disabledPoint.y); await page.mouse.down(); await page.waitForTimeout(600);
    assert.equal(await page.locator('.icon-drag-ghost').count(), 0); await page.mouse.up();
    await page.screenshot({ path: path.join(require('node:os').tmpdir(), 'funtime-icon-delete.png') });
    await page.getByRole('button', { name: 'Remover ⭐ do catálogo', exact: true }).click();
    await page.locator('#undo-icon-removal').click();
    assert.deepEqual(await order(), ['🍺', '⭐', '💧', '🍷']);
    await page.locator('.icon-edit').click(); await page.keyboard.press('Escape');
    await page.evaluate(() => openSettingsView());
    await page.locator('label[for=touch-debug-enabled]').click();
    await page.screenshot({ path: path.join(require('node:os').tmpdir(), 'funtime-touch-debug.png') });
    const downloadPromise = page.waitForEvent('download');
    await page.locator('#export-touch-debug').click();
    const report = JSON.parse(fs.readFileSync(await (await downloadPromise).path(), 'utf8'));
    assert.equal(report.type, 'funtime-touch-debug');
    assert.ok(report.events.some(entry => entry.stage === 'pointer-cancel-ignored'));
    assert.ok(report.events.some(entry => entry.width >= 44));
    assert.equal(JSON.stringify(report).includes('💧'), false);
    assert.equal(JSON.stringify(report).includes('Teste'), false);
    await page.reload();
    await page.waitForFunction(() => typeof state !== 'undefined' && !document.body.classList.contains('boot-pending'));
    assert.deepEqual(await order(), ['🍺', '⭐', '💧', '🍷']);
    assert.equal(await page.locator('#touch-debug-enabled').isChecked(), false);
    assert.equal(await page.locator('#export-touch-debug').isDisabled(), true);
    const longCatalog = Array.from({ length: 100 }, (_, index) => String.fromCodePoint(0x1f400 + index));
    await page.evaluate(catalog => { persistIconCatalog(catalog); openEditDrinkDialog('d'); }, longCatalog);
    const grid = await page.locator('#icon-options').boundingBox();
    // Deslize rápido continua nativo, sem iniciar arraste.
    await touch('touchStart', { x: grid.x + grid.width - 30, y: grid.y + 25 });
    await touch('touchMove', { x: grid.x + grid.width - 38, y: grid.y + 25 });
    for (let i = 1; i <= 5; i++) await touch('touchMove', { x: grid.x + grid.width - 30 - i * 35, y: grid.y + 25 });
    await touch('touchEnd');
    await page.waitForFunction(() => iconOptions.scrollLeft > 0);
    assert.deepEqual(await order(), longCatalog);
    assert.equal(await page.locator('.icon-drag-ghost').count(), 0);
    await page.waitForFunction(() => {
      const left = iconOptions.scrollLeft;
      window.iconStableScroll = window.iconLastScroll === left ? (window.iconStableScroll || 0) + 1 : 0;
      window.iconLastScroll = left;
      return window.iconStableScroll > 8;
    });
    await page.evaluate(() => { iconOptions.scrollLeft = 0; });
    await begin(longCatalog[0]);
    await page.mouse.move(grid.x + grid.width - 4, grid.y + 25, { steps: 5 });
    await page.waitForFunction(() => iconOptions.scrollLeft > 180);
    assert.deepEqual(await order(), longCatalog); await page.mouse.up();
    assert.ok((await order()).indexOf(longCatalog[0]) > 2);
    await page.locator('#undo-icon-reorder').click(); assert.deepEqual(await order(), longCatalog);
    await page.emulateMedia({ reducedMotion: 'reduce' });
    assert.equal(await card(longCatalog[0]).evaluate(node => getComputedStyle(node.parentElement).transitionDuration), '0s');
    await page.evaluate(() => { persistIconCatalog([]); buildIconPicker('💧'); });
    await page.locator('.icon-edit').click(); assert.equal(await page.locator('.icon-remove:visible').count(), 0);
    assert.equal(await selected(), '💧');
    await page.locator('.icon-edit').click(); await page.locator('.icon-add').click();
    assert.equal(await page.locator('#icon-add-panel').isVisible(), true);
    assert.deepEqual(errors, []);
  } finally {
    await browser.close();
    await new Promise(resolve => server.close(resolve));
  }
});
