const { test } = require('node:test');
const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const { createDevServer } = require('../scripts/dev-server.cjs');
test('evento completo, navegação fixa, histórico, backup e persistência', { timeout: 90000 }, async () => {
  const server = createDevServer(); await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto(`http://127.0.0.1:${server.address().port}/funtime/`);
    await page.getByRole('button', { name: 'Começar sem dados', exact: true }).click();
    for (const box of await page.locator('#terms-form input[type=checkbox]').all()) await box.check();
    await page.locator('#terms-continue').click();
    await page.waitForFunction(() => !document.body.classList.contains('boot-pending'));
    await page.evaluate(() => {
      state.drinks = ['old', 'active', 'new'].map(id => ({ id, name: id === 'old' ? 'Cerveja' : id === 'active' ? 'Em contagem' : 'Vinho', icon: id === 'old' ? '🍺' : '🍷', intervalMinutes: 60, askDoseSize: false }));
      state.events = [{ id: 'old-dose', drinkId: 'old', consumedAt: Date.now() - 604800000, intervalMinutes: 60 }, { id: 'active-dose', drinkId: 'active', consumedAt: Date.now() - 300000, intervalMinutes: 60 }]; saveData(); render();
    });
    await page.screenshot({ path: require('node:path').join(require('node:os').tmpdir(), 'funtime-occasion-home.png') });
    await page.locator('#nav-occasion').click();
    assert.equal(await page.locator('#nav-occasion').getAttribute('aria-current'), 'page');
    await page.getByRole('button', { name: 'Iniciar evento', exact: true }).click();
    await page.locator('#occasion-name').fill('Aniversário do João');
    await page.evaluate(() => { globalThis.realSetItem = Storage.prototype.setItem; Storage.prototype.setItem = () => { throw new Error('quota'); }; });
    await page.locator('#occasion-submit').click();
    assert.equal(await page.locator('#occasion-form-error').isVisible(), true);
    assert.equal(await page.evaluate(() => state.occasions.length), 0);
    await page.evaluate(() => { Storage.prototype.setItem = realSetItem; });
    await page.locator('#occasion-submit').click();
    assert.equal(await page.evaluate(() => state.currentView), 'home');
    assert.ok((await page.locator('[data-drink-id=old]').getAttribute('class')).includes('neutral'));
    assert.match(await page.locator('[data-drink-id=active] .drink-status').textContent(), /anterior ao evento/);
    const id = await page.evaluate(() => state.occasions[0].id);
    await page.evaluate(() => registerDrinkAt('new', Date.now()));
    assert.equal(await page.evaluate(() => state.events.at(-1).occasionId), id);
    await page.locator('#nav-occasion').click();
    await page.screenshot({ path: require('node:path').join(require('node:os').tmpdir(), 'funtime-occasion-active.png') });
    await page.getByRole('button', { name: 'Ver registros', exact: true }).click();
    assert.equal(await page.locator('.history-event').count(), 1);
    assert.match(await page.locator('.history-event').textContent(), /Aniversário do João/);
    const data = await page.evaluate(() => buildCurrentAppData());
    const validated = await page.evaluate(data => validateBackupPayload({ type: BACKUP_EXPORT_TYPE, formatVersion: 2, data }), data);
    assert.deepEqual(validated.occasions, data.occasions);
    await page.locator('#nav-occasion').click();
    await page.getByRole('button', { name: 'Encerrar evento', exact: true }).click();
    await page.locator('#app-confirm-accept').click();
    await page.waitForFunction(() => state.currentView === 'home');
    assert.ok((await page.locator('[data-drink-id=new]').getAttribute('class')).includes('waiting'));
    await page.evaluate(() => { state.events.find(record => record.drinkId === 'new').intervalMinutes = 0; saveData(); render(); });
    assert.ok((await page.locator('[data-drink-id=new]').getAttribute('class')).includes('neutral'));
    await page.reload(); await page.waitForFunction(() => typeof state !== 'undefined' && state.occasions?.length === 1);
    assert.equal(await page.evaluate(() => state.occasions[0].name), 'Aniversário do João');
    await page.locator('#nav-occasion').click();
    await page.getByRole('button', { name: 'Reabrir', exact: true }).click();
    await page.locator('#app-confirm-accept').click();
    await page.waitForFunction(() => state.occasions[0].endedAt === null);
    await page.getByRole('button', { name: 'Encerrar evento', exact: true }).click();
    await page.locator('#app-confirm-accept').click();
    await page.waitForFunction(() => state.currentView === 'home');
    await page.locator('#nav-occasion').click();
    await page.getByRole('button', { name: 'Iniciar evento', exact: true }).click();
    await page.locator('#occasion-name').fill('Próximo evento');
    await page.locator('#occasion-submit').click();
    await page.waitForFunction(() => state.occasions.length === 2);
    await page.locator('#nav-occasion').click();
    await page.getByRole('button', { name: 'Excluir evento', exact: true }).first().click();
    await page.locator('#app-confirm-accept').click();
    await page.waitForFunction(() => state.occasions.length === 1);
    await page.getByRole('button', { name: 'Editar', exact: true }).click();
    await page.locator('#occasion-start').evaluate(input => input.parentElement.open = true);
    assert.equal(await page.getByRole('spinbutton', { name: 'Hora de início', exact: true }).isVisible(), true);
    await page.screenshot({ path: require('node:path').join(require('node:os').tmpdir(), 'funtime-occasion-editor.png') });
    await page.locator('#occasion-name').fill('Aniversário do João — editado');
    await page.locator('#occasion-submit').click();
    await page.getByRole('button', { name: 'Excluir evento', exact: true }).click();
    await page.locator('#app-confirm-accept').click();
    await page.waitForFunction(() => state.occasions.length === 0);
    assert.equal(await page.evaluate(() => state.events.length), 3);
    assert.equal(await page.evaluate(() => state.events.at(-1).occasionId), null);
    await page.evaluate(() => { closeHistoryView(); openDrinkMenuDialog('old'); openLogDialog('old'); setLogDurationPicker(0, 5); });
    const countBefore = await page.evaluate(() => state.events.length);
    await page.locator('#log-form button[type=submit]').click();
    await page.waitForFunction(() => state.currentView === 'home' && !document.querySelector('dialog[open]'));
    assert.equal(await page.evaluate(() => state.events.length), countBefore + 1);
    const logId = await page.evaluate(() => state.events.at(-1).id);
    await page.evaluate(() => {
      commitOccasions([{ id: 'cover', name: 'Período ampliado', startedAt: Date.now() - 60000, endedAt: null }]);
      openOccasionEditor('cover');
      const input = document.getElementById('occasion-start'); input.value = occasionInput(Date.now() - 360000); input.dispatchEvent(new Event('input', { bubbles: true }));
    });
    await page.locator('#occasion-submit').click();
    assert.equal(await page.evaluate(id => state.events.find(record => record.id === id).occasionId, logId), 'cover');
    await page.evaluate(() => openOccasionHistory('cover'));
    assert.ok(await page.locator('.history-event').count() >= 1);
    await page.reload(); await page.waitForFunction(() => typeof state !== 'undefined' && state.occasions?.length === 1);
    assert.equal(await page.evaluate(id => state.events.find(record => record.id === id).occasionId, logId), 'cover');
    assert.deepEqual(errors, []);
  } finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
});
